# Generated by Django 2.0.4 on 2018-04-29 15:52

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180429_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=None, upload_to=store.models.get_path),
            preserve_default=False,
        ),
    ]
