# Generated by Django 2.0.4 on 2018-05-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_productimage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
