# Generated by Django 2.0.4 on 2018-04-29 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180428_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='properties',
        ),
        migrations.AddField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='store.Product'),
        ),
    ]
