# Generated by Django 2.0.3 on 2018-04-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180413_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mateial',
            new_name='material',
        ),
    ]
