# Generated by Django 2.0.4 on 2018-04-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20180426_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(choices=[('front', 'front image'), ('back', 'back image'), ('other', 'other')], default='other', max_length=200),
        ),
    ]
