# Generated by Django 2.0.4 on 2018-05-23 09:08

from django.db import migrations, models
import store.helpers.validators
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20180522_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=store.models.get_path, validators=[store.helpers.validators.file_size]),
        ),
    ]
