# Generated by Django 2.0.4 on 2018-05-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20180524_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperty',
            name='slug',
        ),
    ]
