# Generated by Django 2.0.4 on 2018-05-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_productproperty_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filters',
        ),
        migrations.AddField(
            model_name='filteroption',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='filter_options',
            field=models.ManyToManyField(blank=True, related_name='filtered_products', to='store.FilterOption'),
        ),
    ]
