# Generated by Django 2.0.4 on 2018-04-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-5B4JNN', max_length=200, unique=True),
        ),
    ]
