# Generated by Django 2.0.4 on 2018-05-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_productrate_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrate',
            name='session_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
