# Generated by Django 2.0.4 on 2018-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180429_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selectedproduct',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
