# Generated by Django 2.0.4 on 2018-06-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_basket_paid_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrate',
            old_name='rate',
            new_name='rate_beauty',
        ),
        migrations.AddField(
            model_name='productrate',
            name='rate_fabric',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productrate',
            name='rate_manner',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productrate',
            name='rate_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
