# Generated by Django 2.0.4 on 2018-04-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('customer', '0002_auto_20180426_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_comments', to='store.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Color'),
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Size'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='lovers', to='store.Product'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-VHZXE2', max_length=200, unique=True),
        ),
    ]
