# Generated by Django 2.0.3 on 2018-04-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_basket_selectedprodect'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedprodect',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-FSG9CR', max_length=200, unique=True),
        ),
    ]
