# Generated by Django 2.0.3 on 2018-04-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180413_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-0NFKKZ', max_length=200, unique=True),
        ),
    ]
