# Generated by Django 2.0.4 on 2018-06-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180613_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='paid_at',
            new_name='paid_online_at',
        ),
        migrations.AddField(
            model_name='basket',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='how_much_paid_at_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basket',
            name='how_much_paid_online',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basket',
            name='paid_at_home_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('pay_at_home', 'پرداخت درب منزل'), ('pay_online', 'پرداخت آنلاین')], max_length=200, null=True),
        ),
    ]
