# Generated by Django 2.0.3 on 2018-04-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20180413_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-TDD3C7', max_length=200, unique=True),
        ),
    ]
