# Generated by Django 2.0.4 on 2018-04-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20180426_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-XGAR7Q', max_length=200, unique=True),
        ),
    ]
