# Generated by Django 2.0.4 on 2018-04-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20180426_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-OLSQ5H', max_length=200, unique=True),
        ),
    ]
