# Generated by Django 2.0.3 on 2018-04-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20180413_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-ZEYV0D', max_length=200, unique=True),
        ),
    ]
