# Generated by Django 2.0.4 on 2018-04-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20180426_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('user', 'Normal User'), ('admin', 'Admin User')], default='user', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-IALIJS', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
