# Generated by Django 2.0.3 on 2018-04-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20180413_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-KXS6IF', max_length=200, unique=True),
        ),
    ]
