# Generated by Django 2.0.4 on 2018-04-27 04:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20180426_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('user', 'Normal User'), ('admin', 'Admin User')], default='user', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
