# Generated by Django 2.0.4 on 2018-04-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20180414_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-84ZT2W', max_length=200, unique=True),
        ),
    ]
