# Generated by Django 2.0.4 on 2018-04-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20180427_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedproduct',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
