# Generated by Django 2.0.4 on 2018-04-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20180426_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-WJUYGY', max_length=200, unique=True),
        ),
    ]
