# Generated by Django 2.0.4 on 2018-04-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20180426_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-RAMZOJ', max_length=200, unique=True),
        ),
    ]
