# Generated by Django 2.0.4 on 2018-04-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20180426_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-D0BQKK', max_length=200, unique=True),
        ),
    ]
