# Generated by Django 2.0.4 on 2018-04-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20180426_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-MWEEBK', max_length=200, unique=True),
        ),
    ]
