# Generated by Django 2.0.4 on 2018-04-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20180426_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='code',
            field=models.CharField(default='HINATA-Q52WIN', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='selectedproduct',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Color'),
        ),
        migrations.AlterField(
            model_name='selectedproduct',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Size'),
        ),
    ]
